[package]
name = "envoy"
version = "0.1.3"
authors = ["Dave Herman <david.herman@gmail.com>"]
description = "Conveniences for manipulating environment variables."
readme = "README.md"
repository = "https://github.com/dherman/envoy"
license = "MIT/Apache-2.0"

[dependencies]
